- name: Create devops directory
  hosts: all
  become: yes
  tasks:
    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory
        mode: '0755'
