# Install, start and enable http service on ubuntu server

---
- name: Install HTTP server
  hosts: n6
  become: yes

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        
    - name: Start apache2 
      service:
            name: apache2
            state: started

    - name: Enable apache2 
      service:
            name: apache2
            enabled: yes
        